# Blog settings
title: Loris Bergeron's Blog
description: > # This means to ignore newlines until "show_excerpts:"
  Programming, Open Source, AI, Microsoft, DevOps, .NET and More.

show_excerpts: true # Set to true to show excerpts on the homepage

# Theme settings
minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: lrsbrgrn
    github:  lorisbergeron
    linkedin: lorisbergeron
    telegram: ""

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in order as they should show up
header_pages:
  - disclaimer.md

# Build settings
theme: minima
paginate: 10
paginate_path: posts/page:num/

# Google Analytics
google_analytics: UA-170074037-1

# Plugins statement
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate